object Versions {
    const val kotlin = "1.4.32"
    const val springDepsManagerPlugin = "1.0.11.RELEASE"
    const val protobufPlugin = "0.8.10"
    const val logback = "1.2.3"
    const val cucumber = "4.3.1"
    const val kluent = "1.53"
    const val kubernetesJavaClient = "7.0.0"
    const val googleAuth = "0.19.0"
    const val googleBigquery = "1.101.0"
    const val mysql = "5.1.13"
    const val jackson = "2.12.3"
    const val springBoot = "2.5.2"
    const val springWeb = "5.3.8"
    const val checkout = "3.4.0"
    const val assertj = "3.19.0"
    const val protobuf = "3.10.0"
    const val openApi = "1.5.9"
    const val jUnit = "4.13.2"
    const val jdiDark = "1.1.9"
    const val testNG = "7.4.0"
}